Repository apricity2u/muse, pull requests merged in 2025-05, with the labels that each got.

#5 feat: common-components
  client/package-lock.json
  client/package.json
  client/public/edit.svg
  client/public/heart.svg
  client/public/link.svg
  client/public/notebook.svg
  client/public/user.svg
  client/src/api/bookApi.js
  client/src/assets/reset.png
  client/src/assets/search.png
  client/src/components/board/DashBoard.jsx
  client/src/components/board/SearchBoard.jsx
  client/src/components/board/SearchBoard.module.css
  client/src/components/button/AlertButton.jsx
  client/src/components/button/AlertButton.module.css
  client/src/components/button/AlignButton.jsx
  client/src/components/button/AlignButton.module.css
  client/src/components/button/CircleButton.jsx
  client/src/components/button/CircleButton.module.css
  client/src/components/button/DropBoxButton.jsx
  client/src/components/button/DropBoxButton.module.css
  client/src/components/button/LoginButton.jsx
  client/src/components/button/LoginButton.module.css
  client/src/components/button/RoundButton.jsx
  client/src/components/button/RoundButton.module.css
  client/src/components/button/SubTabButton.jsx
  client/src/components/button/SubTabButton.module.css
  client/src/components/button/TabButton.jsx
  client/src/components/button/TabButton.module.css
  client/src/components/button/TabDropBoxButton.jsx
  client/src/components/button/TabDropBoxButton.module.css
  client/src/components/content/BookDetailContent.jsx
  client/src/components/content/BookDetailContent.module.css
  client/src/components/item/SearchResultItem.jsx
  client/src/components/item/SearchResultItem.module.css
  client/src/components/modal/AlertModal.jsx
  client/src/components/modal/AlertModal.module.css
  client/src/styles/index.css
  client/src/styles/reset.css
Labels: chore, feat, refactor

#6 feat: common components
  client/public/logo.png
  client/src/api/authApi.js
  client/src/components/Logo.jsx
  client/src/components/Logo.module.css
  client/src/components/button/RoundButton.jsx
  client/src/components/button/RoundButton.module.css
  client/src/components/button/TabButton.jsx
  client/src/components/header/Header.jsx
  client/src/components/header/Header.module.css
  client/src/store/slices/authSlice.js
  client/src/store/store.js
Labels: feat, refactor

#13 feat: common components
  client/public/heart.svg
  client/public/vite.svg
  client/src/assets/edit.svg
  client/src/assets/heart.png
  client/src/assets/link.svg
  client/src/assets/notebook.svg
  client/src/assets/user.svg
  client/src/components/Logo.jsx
  client/src/components/board/SearchBoard.jsx
  client/src/components/board/SearchBoard.module.css
  client/src/components/button/CircleButton.jsx
  client/src/components/button/TabDropBoxButton.jsx
  client/src/components/button/TabDropBoxButton.module.css
  client/src/components/header/Header.jsx
  client/src/components/header/Header.module.css
  client/src/components/header/SubHeader.jsx
  client/src/components/item/BookDetailItem.jsx
  client/src/components/item/BookDetailItem.module.css
  client/src/components/modal/SearchModal.jsx
  client/src/components/modal/SearchModal.module.css
  client/src/store/slices/authSlice.js
Labels: feat, refactor

#14 feat: implement login detail login
  api/Dockerfile
  api/build.gradle
  api/docker-compose.yml
  api/src/main/java/com/example/muse/domain/auth/AuthService.java
  api/src/main/java/com/example/muse/domain/auth/LoginResponseDto.java
  api/src/main/java/com/example/muse/domain/auth/OAuth2SuccessHandler.java
  api/src/main/java/com/example/muse/global/common/config/RedisConfig.java
  api/src/main/java/com/example/muse/global/security/jwt/JwtTokenUtil.java
  api/src/main/java/com/example/muse/global/security/jwt/TokenRedisService.java
  api/src/main/resources/application.properties
Labels: feat

#15 refactor: login refactoring
  api/build.gradle
  api/src/main/java/com/example/muse/domain/auth/AuthController.java
  api/src/main/java/com/example/muse/domain/auth/AuthService.java
  api/src/main/java/com/example/muse/domain/auth/OAuth2SuccessHandler.java
  api/src/main/java/com/example/muse/domain/auth/TokenResponseWriter.java
  api/src/main/java/com/example/muse/domain/member/MemberRepository.java
  api/src/main/java/com/example/muse/global/common/config/JwtConfig.java
  api/src/main/java/com/example/muse/global/security/jwt/JwtAuthenticationFilter.java
  api/src/main/java/com/example/muse/global/security/jwt/JwtTokenUtil.java
  api/src/main/java/com/example/muse/global/security/jwt/TokenRedisService.java
  api/src/main/resources/application.properties
  api/src/test/java/com/example/muse/global/common/config/JwtConfigTest.java
Labels: refactor

#18 feat: reissue
  api/src/main/java/com/example/muse/domain/auth/AuthController.java
  api/src/main/java/com/example/muse/domain/auth/AuthService.java
  api/src/main/java/com/example/muse/domain/auth/OAuth2SuccessHandler.java
  api/src/main/java/com/example/muse/global/security/jwt/JwtAuthenticationFilter.java
  api/src/main/java/com/example/muse/global/security/jwt/JwtTokenUtil.java
  api/src/main/java/com/example/muse/global/security/jwt/TokenRedisService.java
Labels: feat

#19 feat: common components
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/api/bookApi.js
  client/src/api/reviewApi.js
  client/src/assets/book.png
  client/src/assets/heart_filled.png
  client/src/assets/left.png
  client/src/assets/menu-dots-vertical.png
  client/src/assets/right.png
  client/src/components/button/CircleButton.jsx
  client/src/components/button/DropBoxButton.jsx
  client/src/components/button/DropBoxButton.module.css
  client/src/components/button/PaginationButton.jsx
  client/src/components/button/PaginationButton.module.css
  client/src/components/card/BookCard.jsx
  client/src/components/card/BookCard.module.css
  client/src/components/card/ReviewCard.jsx
  client/src/components/card/ReviewCard.module.css
  client/src/components/header/Header.module.css
  client/src/components/item/BookDetailItem.jsx
  client/src/components/item/BookDetailItem.module.css
  client/src/components/list/BookCardLists.jsx
  client/src/components/list/BookCardLists.module.css
  client/src/components/list/ReviewCardLists.jsx
  client/src/components/list/ReviewCardLists.module.css
  client/src/components/modal/AlertModal.jsx
  client/src/components/modal/AlertModal.module.css
  client/src/store/slices/authSlice.js
  client/src/store/slices/bookSlice.js
  client/src/store/store.js
  client/src/styles/index.css
Labels: feat, refactor

#20 feat: 메인페이지 구현
  client/src/api/reviewApi.js
  client/src/assets/dog.jpg
  client/src/assets/harry.jpg
  client/src/assets/main.mp4
  client/src/assets/scroll.png
  client/src/components/header/Header.module.css
  client/src/components/list/ReviewCardLists.jsx
  client/src/components/list/ReviewCardLists.module.css
  client/src/components/modal/AlertModal.module.css
  client/src/components/modal/SearchModal.jsx
  client/src/components/modal/SearchModal.module.css
  client/src/pages/Home.jsx
  client/src/pages/styles/Home.module.css
  client/src/styles/index.css
Labels: feat, refactor, fix

#21 feat: Implement write review
  api/src/main/java/com/example/muse/MuseApplication.java
  api/src/main/java/com/example/muse/domain/book/Book.java
  api/src/main/java/com/example/muse/domain/book/BookController.java
  api/src/main/java/com/example/muse/domain/book/BookRepository.java
  api/src/main/java/com/example/muse/domain/book/BookService.java
  api/src/main/java/com/example/muse/domain/book/dto/SearchBookResponseDto.java
  api/src/main/java/com/example/muse/domain/image/Image.java
  api/src/main/java/com/example/muse/domain/image/ImageRepository.java
  api/src/main/java/com/example/muse/domain/image/ImageService.java
  api/src/main/java/com/example/muse/domain/image/ImageType.java
  api/src/main/java/com/example/muse/domain/review/Review.java
  api/src/main/java/com/example/muse/domain/review/ReviewController.java
  api/src/main/java/com/example/muse/domain/review/ReviewRepository.java
  api/src/main/java/com/example/muse/domain/review/ReviewService.java
  api/src/main/java/com/example/muse/domain/review/dto/CreateReviewRequestDto.java
  api/src/main/java/com/example/muse/domain/review/dto/CreateReviewResponseDto.java
  api/src/main/java/com/example/muse/domain/s3/S3Config.java
  api/src/main/java/com/example/muse/domain/s3/S3Service.java
Labels: feat

#23 feat: lookup main review
  api/src/main/java/com/example/muse/domain/auth/dto/LoginResponseDto.java
  api/src/main/java/com/example/muse/domain/book/Book.java
  api/src/main/java/com/example/muse/domain/book/dto/BookDto.java
  api/src/main/java/com/example/muse/domain/like/Likes.java
  api/src/main/java/com/example/muse/domain/member/Member.java
  api/src/main/java/com/example/muse/domain/review/Review.java
  api/src/main/java/com/example/muse/domain/review/ReviewController.java
  api/src/main/java/com/example/muse/domain/review/ReviewRepository.java
  api/src/main/java/com/example/muse/domain/review/ReviewService.java
  api/src/main/java/com/example/muse/domain/review/dto/GetMainReviewsResponseDto.java
  api/src/main/java/com/example/muse/domain/review/dto/ReviewCardResponseDto.java
  api/src/main/java/com/example/muse/domain/review/dto/ReviewDto.java
  api/src/main/resources/application.properties
Labels: feat

#24 feat: lookup user review
  api/src/main/java/com/example/muse/domain/book/dto/BookDto.java
  api/src/main/java/com/example/muse/domain/review/ReviewController.java
  api/src/main/java/com/example/muse/domain/review/ReviewRepository.java
  api/src/main/java/com/example/muse/domain/review/ReviewService.java
  api/src/main/java/com/example/muse/domain/review/dto/GetReviewsResponseDto.java
  api/src/main/java/com/example/muse/domain/review/dto/ReviewDto.java
Labels: feat

#25 feat: extend login response
  api/src/main/java/com/example/muse/domain/auth/AuthController.java
  api/src/main/java/com/example/muse/domain/auth/AuthService.java
  api/src/main/java/com/example/muse/domain/auth/dto/LoginResponseDto.java
  api/src/main/java/com/example/muse/domain/image/Image.java
  api/src/main/java/com/example/muse/domain/image/ImageRepository.java
  api/src/main/java/com/example/muse/domain/member/Member.java
Labels: feat

#27 fix: 이미지 업로드 시 유저 정보 추가
  api/src/main/java/com/example/muse/domain/image/ImageService.java
  api/src/main/java/com/example/muse/domain/member/MemberService.java
  api/src/main/java/com/example/muse/domain/review/ReviewService.java
Labels: fix

#26 feat: lookup profile
  api/src/main/java/com/example/muse/domain/member/Member.java
  api/src/main/java/com/example/muse/domain/member/MemberController.java
  api/src/main/java/com/example/muse/domain/member/MemberService.java
  api/src/main/java/com/example/muse/domain/member/dto/GetProfileResponseDto.java
Labels: feat

#29 feat: 리뷰 삭제 기능 구현
  api/src/main/java/com/example/muse/domain/review/ReviewController.java
  api/src/main/java/com/example/muse/domain/review/ReviewService.java
Labels: feat

#30 feat: get liked reviews
  api/src/main/java/com/example/muse/domain/review/ReviewController.java
  api/src/main/java/com/example/muse/domain/review/ReviewRepository.java
  api/src/main/java/com/example/muse/domain/review/ReviewService.java
  api/src/main/java/com/example/muse/domain/review/dto/GetLikedReviewsResponseDto.java
Labels: feat

#32 feat: review unlike
  api/src/main/java/com/example/muse/domain/like/LikesRepository.java
  api/src/main/java/com/example/muse/domain/like/LikesService.java
  api/src/main/java/com/example/muse/domain/review/ReviewController.java
  api/src/main/java/com/example/muse/domain/review/ReviewService.java
Labels: feat

#34 feat: book unlike
  api/src/main/java/com/example/muse/domain/book/BookController.java
  api/src/main/java/com/example/muse/domain/book/BookService.java
  api/src/main/java/com/example/muse/domain/like/LikesRepository.java
  api/src/main/java/com/example/muse/domain/like/LikesService.java
  api/src/main/java/com/example/muse/domain/review/ReviewService.java
Labels: feat

#37 feat: lookup book
  api/docker-compose.yml
  api/src/main/java/com/example/muse/domain/book/Book.java
  api/src/main/java/com/example/muse/domain/book/BookController.java
  api/src/main/java/com/example/muse/domain/book/BookService.java
  api/src/main/java/com/example/muse/domain/book/dto/GetBookResponseDto.java
Labels: feat

#39 feat: get liked books
  api/src/main/java/com/example/muse/domain/book/BookController.java
  api/src/main/java/com/example/muse/domain/book/BookRepository.java
  api/src/main/java/com/example/muse/domain/book/BookService.java
  api/src/main/java/com/example/muse/domain/review/ReviewController.java
  api/src/main/java/com/example/muse/domain/review/ReviewRepository.java
  api/src/main/java/com/example/muse/domain/review/ReviewService.java
Labels: feat

#40 fix: lookup user books
  api/src/main/java/com/example/muse/domain/book/BookRepository.java
  api/src/main/java/com/example/muse/domain/book/BookService.java
  api/src/main/java/com/example/muse/domain/book/dto/BookDto.java
  api/src/main/java/com/example/muse/domain/book/dto/SearchBookResponseDto.java
Labels: feat

#45 feat: deploy jenkins docker
  Jenkinsfile
Labels: feat

#46 fix: 젠킨스 파일 수정
  Jenkinsfile
Labels: fix

#49 fix: 젠킨스 파일 수정
  Jenkinsfile
Labels: fix

#50 fix: 젠킨스 파일 수정
  Jenkinsfile
Labels: fix
