Repository apricity2u/muse, pull requests merged in 2025-06, with the labels that each got.

#53 feat: 도서 데이터 스크랩
  api/src/main/java/com/example/muse/domain/book/Book.java
  client/Dockerfile
  scrap/.gitignore
  scrap/api.py
  scrap/db.py
  scrap/main.py
  scrap/requirments.txt
Labels: feat, fix

#54 fix: oauth redirect endpoint
  api/src/main/java/com/example/muse/global/security/config/SecurityConfig.java
  api/src/main/resources/application.properties
Labels: fix

#59 refactor: refactor authSlice memberId
  client/src/components/common/header/Header.module.css
  client/src/store/slices/authSlice.js
Labels: refactor

#60 feat: update profile
  api/src/main/java/com/example/muse/domain/member/Member.java
  api/src/main/java/com/example/muse/domain/member/MemberController.java
  api/src/main/java/com/example/muse/domain/member/MemberService.java
Labels: feat

#63 fix: api 연동 확인 및 오류 해결
  client/src/api/bookApi.js
  client/src/api/reviewApi.js
  client/src/components/common/button/CircleButton.jsx
  client/src/components/common/button/DropBoxButton.module.css
  client/src/components/common/button/TabButton.module.css
  client/src/components/common/card/BookCard.jsx
  client/src/components/common/card/BookCard.module.css
  client/src/components/common/card/ReviewCard.jsx
  client/src/components/common/card/review_card/CardBack.jsx
  client/src/components/common/card/review_card/CardBack.module.css
  client/src/components/common/card/review_card/CardFront.jsx
  client/src/components/common/card/review_card/CardFront.module.css
  client/src/components/common/content/BookDetailContent.jsx
  client/src/components/common/header/Header.module.css
  client/src/components/common/image/Logo.module.css
  client/src/components/common/item/BookDetailItem.jsx
  client/src/components/common/list/BookCardLists.module.css
  client/src/components/common/list/ReviewCardLists.jsx
  client/src/components/review_create/Card.jsx
  client/src/components/review_create/ImageUploader.jsx
  client/src/pages/Home.jsx
  client/src/pages/ReviewCreate.jsx
  client/src/pages/UserLikes.jsx
  client/src/pages/UserLikes.module.css
  client/src/pages/UserReviews.jsx
  client/src/pages/UserReviews.module.css
Labels: refactor, fix

#66 feat: protected router and notfound
  client/src/components/NotFound.jsx
  client/src/components/NotFound.module.css
  client/src/layout/ProtectedLayout.jsx
  client/src/pages/Home.jsx
  client/src/pages/Home.module.css
  client/src/router/index.jsx
  client/src/styles/index.css
Labels: feat

#70 fix: image loic
  api/src/main/java/com/example/muse/domain/image/dto/ImageDto.java
  api/src/main/java/com/example/muse/domain/review/ReviewService.java
  api/src/main/java/com/example/muse/global/security/handler/JwtAuthenticationEntryPoint.java
Labels: fix

#73 feat: book detail page
  api/src/main/java/com/example/muse/domain/book/dto/BookDto.java
  api/src/main/java/com/example/muse/domain/book/dto/GetBookResponseDto.java
  api/src/main/java/com/example/muse/global/security/handler/JwtAuthenticationEntryPoint.java
  api/src/main/java/com/example/muse/global/security/jwt/JwtAuthenticationFilter.java
  api/src/main/java/com/example/muse/global/security/jwt/JwtTokenUtil.java
  client/src/api/axios.js
  client/src/api/reviewApi.js
  client/src/components/common/button/LineButton.jsx
  client/src/components/common/button/Linebutton.module.css
  client/src/components/common/card/ReviewCard.jsx
  client/src/components/common/list/ReviewCardLists.module.css
  client/src/pages/BookDetail.jsx
  client/src/pages/BookDetail.module.css
  client/src/styles/index.css
Labels: feat

#74 feat: handle exception
  api/src/main/java/com/example/muse/domain/auth/AuthService.java
  api/src/main/java/com/example/muse/domain/book/BookService.java
  api/src/main/java/com/example/muse/domain/image/ImageService.java
  api/src/main/java/com/example/muse/domain/like/LikesService.java
  api/src/main/java/com/example/muse/domain/member/MemberService.java
  api/src/main/java/com/example/muse/domain/review/ReviewController.java
  api/src/main/java/com/example/muse/domain/review/ReviewService.java
  api/src/main/java/com/example/muse/domain/s3/S3Service.java
  api/src/main/java/com/example/muse/global/common/dto/ApiResponse.java
  api/src/main/java/com/example/muse/global/common/exception/CustomBadRequestException.java
  api/src/main/java/com/example/muse/global/common/exception/CustomException.java
  api/src/main/java/com/example/muse/global/common/exception/CustomJwtException.java
  api/src/main/java/com/example/muse/global/common/exception/CustomLoginException.java
  api/src/main/java/com/example/muse/global/common/exception/CustomNotFoundException.java
  api/src/main/java/com/example/muse/global/common/exception/CustomOauthException.java
  api/src/main/java/com/example/muse/global/common/exception/CustomReissueException.java
  api/src/main/java/com/example/muse/global/common/exception/CustomS3Exception.java
  api/src/main/java/com/example/muse/global/common/exception/CustomUnauthorizedException.java
  api/src/main/java/com/example/muse/global/common/exception/ErrorCode.java
  api/src/main/java/com/example/muse/global/common/exception/GlobalExceptionHandler.java
  api/src/main/java/com/example/muse/global/security/config/SecurityConfig.java
  api/src/main/java/com/example/muse/global/security/config/SecurityPathConfig.java
  api/src/main/java/com/example/muse/global/security/jwt/JwtConfig.java
  api/src/main/java/com/example/muse/global/security/jwt/JwtTokenUtil.java
Labels: feat, refactor, fix

#75 docs: tidy up docs
  .env.example
  README.md
  api/.env.example
Labels: docs

#76 feat: be optimization
  api/src/main/java/com/example/muse/domain/auth/OAuth2SuccessHandler.java
  api/src/main/java/com/example/muse/domain/book/Book.java
  api/src/main/java/com/example/muse/domain/book/BookRepository.java
  api/src/main/java/com/example/muse/domain/book/BookService.java
  api/src/main/java/com/example/muse/domain/image/Image.java
  api/src/main/java/com/example/muse/domain/image/ImageService.java
  api/src/main/java/com/example/muse/domain/like/LikesRepository.java
  api/src/main/java/com/example/muse/domain/member/Member.java
  api/src/main/java/com/example/muse/domain/member/MemberService.java
  api/src/main/java/com/example/muse/domain/member/dto/MemberProfileDto.java
  api/src/main/java/com/example/muse/domain/review/ReviewRepository.java
  api/src/main/java/com/example/muse/domain/review/ReviewService.java
  api/src/main/java/com/example/muse/global/aop/Timer.java
  api/src/main/java/com/example/muse/global/common/config/AopConfig.java
  api/src/main/java/com/example/muse/global/common/exception/CustomJwtException.java
  api/src/main/java/com/example/muse/global/security/jwt/JwtAuthenticationFilter.java
  docker-compose.yml
Labels: feat, refactor

#78 refactor: frontend css
  client/src/components/common/button/PaginationButton.module.css
  client/src/components/common/button/TabButton.module.css
  client/src/components/common/button/TabDropBoxButton.module.css
  client/src/components/common/card/ReviewCard.module.css
  client/src/components/common/header/Header.jsx
  client/src/components/common/header/Header.module.css
  client/src/components/common/image/Logo.module.css
  client/src/components/common/list/BookCardLists.module.css
  client/src/components/common/list/ReviewCardLists.module.css
  client/src/pages/BookDetail.jsx
  client/src/pages/BookDetail.module.css
  client/src/pages/Home.module.css
  client/src/pages/Login.module.css
  client/src/pages/UserLikes.module.css
  client/src/pages/UserReviews.module.css
  client/src/styles/index.css
Labels: refactor, fix

#77 fix: image lifecycle
  api/src/main/java/com/example/muse/domain/auth/AuthService.java
  api/src/main/java/com/example/muse/domain/book/Book.java
  api/src/main/java/com/example/muse/domain/book/BookService.java
  api/src/main/java/com/example/muse/domain/book/dto/BookDto.java
  api/src/main/java/com/example/muse/domain/image/Image.java
  api/src/main/java/com/example/muse/domain/image/ImageRepository.java
  api/src/main/java/com/example/muse/domain/image/ImageService.java
  api/src/main/java/com/example/muse/domain/like/Likes.java
  api/src/main/java/com/example/muse/domain/member/Member.java
  api/src/main/java/com/example/muse/domain/member/MemberRepository.java
  api/src/main/java/com/example/muse/domain/member/MemberService.java
  api/src/main/java/com/example/muse/domain/member/dto/GetProfileResponseDto.java
  api/src/main/java/com/example/muse/domain/member/dto/MemberProfileDto.java
  api/src/main/java/com/example/muse/domain/review/Review.java
  api/src/main/java/com/example/muse/domain/review/ReviewRepository.java
  api/src/main/java/com/example/muse/domain/review/ReviewService.java
  api/src/main/java/com/example/muse/domain/review/dto/GetLikedReviewsResponseDto.java
  api/src/main/java/com/example/muse/domain/review/dto/GetReviewCardsResponseDto.java
  api/src/main/java/com/example/muse/domain/review/dto/ReviewDto.java
  api/src/main/java/com/example/muse/global/security/config/SecurityPathConfig.java
  api/src/main/resources/application.properties
Labels: feat, refactor, fix

#80 fix: lookup review sort by like
  api/src/main/java/com/example/muse/MuseApplication.java
  api/src/main/java/com/example/muse/domain/book/BookRepository.java
  api/src/main/java/com/example/muse/domain/image/ImageService.java
  api/src/main/java/com/example/muse/domain/review/ReviewRepository.java
  api/src/main/java/com/example/muse/domain/review/ReviewService.java
  api/src/main/java/com/example/muse/domain/review/dto/CreateReviewRequestDto.java
  api/src/main/java/com/example/muse/global/common/service/ImagePrefetchService.java
Labels: feat, fix

#82 fix: S3_PREFIX_LENGTH 값 변경
  api/src/main/java/com/example/muse/domain/review/dto/ReviewCardResponseDto.java
Labels: fix

#84 feat: reissue
  api/src/main/java/com/example/muse/domain/auth/AuthService.java
  api/src/main/java/com/example/muse/domain/auth/dto/LoginResponseDto.java
  api/src/main/java/com/example/muse/domain/member/dto/GetProfileResponseDto.java
Labels: feat

#85 fix: 쿼리 수정
  api/src/main/java/com/example/muse/domain/book/BookController.java
  api/src/main/java/com/example/muse/domain/book/BookRepository.java
  api/src/main/java/com/example/muse/domain/book/BookService.java
  api/src/main/java/com/example/muse/domain/book/dto/GetBookResponseDto.java
  api/src/main/java/com/example/muse/domain/review/ReviewRepository.java
Labels: fix

#86 Fix/lookup users books
  api/src/main/java/com/example/muse/domain/review/ReviewRepository.java
Labels: fix

#88 feat: 데모 로그인 api
  api/src/main/java/com/example/muse/domain/auth/AuthController.java
  client/src/App.jsx
  client/src/pages/Login.jsx
Labels: feat

#89 fix/frontend-improvement
  client/src/components/common/card/ReviewCard.jsx
  client/src/components/common/card/ReviewCard.module.css
  client/src/components/common/card/review_card/CardFront.jsx
  client/src/components/common/item/BookDetailItem.jsx
  client/src/components/common/list/ReviewCardLists.jsx
  client/src/pages/Home.module.css
Labels: fix
