Repository apricity2u/muse, pull requests merged in 2025-07, with the labels that each got.

#92 feat: search book optimization
  api/src/main/java/com/example/muse/domain/book/BookRepository.java
  api/src/main/java/com/example/muse/domain/book/BookService.java
  api/src/main/java/com/example/muse/domain/review/dto/ReviewCardResponseDto.java
  api/src/main/java/com/example/muse/global/common/config/RedisConfig.java
  api/src/main/java/com/example/muse/global/common/service/CachePrefetchService.java
Labels: refactor

#94 fix: BookDetail fetch
  client/src/pages/BookDetail.jsx
Labels: fix

#96 chore: backend cleanup
  .env.example
  api/.env.example
  api/src/main/java/com/example/muse/domain/auth/AuthController.java
  api/src/main/java/com/example/muse/domain/book/BookRepository.java
  api/src/main/java/com/example/muse/domain/book/BookService.java
  api/src/main/java/com/example/muse/global/common/config/SwaggerConfig.java
  api/src/main/java/com/example/muse/global/common/exception/CustomUnauthorizedException.java
  api/src/main/java/com/example/muse/global/common/exception/ErrorCode.java
  api/src/main/java/com/example/muse/global/security/config/SecurityPathConfig.java
  api/src/main/java/com/example/muse/global/security/handler/JwtAuthenticationEntryPoint.java
  api/src/main/resources/application.properties
  docker-compose.yml
Labels: chore

#102 refactor: router protection
  client/src/components/common/button/SubTabButton.jsx
  client/src/pages/Profile.jsx
  client/src/pages/UserLikes.jsx
  client/src/router/index.jsx
Labels: refactor, fix

#103 fix: protection router
  client/src/layout/ProtectedLayout.jsx
Labels: fix
